image: docker:latest

services:
  - name: docker:dind
    command: [ "--insecure-registry=${NEXUS_REGISTRY_HOST}" ]

before_script:
  - docker info
  - docker login -u ${NEXUS_REGISTRY_USER} -p ${NEXUS_REGISTRY_PASSWORD} ${NEXUS_REGISTRY_HOST}

stages:
  - build

build-image:
  stage: build
  script:
    - docker build . --tag=userservice:latest \ 
      --build-arg NEXUS_MAVEN_REPOSITORY_URL=${NEXUS_MAVEN_REPOSITORY_URL} \
      --build-arg NEXUS_REPOSITORY_USER=${NEXUS_REPOSITORY_USER} \
      --build-arg NEXUS_REPOSITORY_PASSWORD=${NEXUS_REPOSITORY_PASSWORD}

    - docker tag userservice:latest ${NEXUS_REGISTRY_HOST}/userservice:latest
    - docker push ${NEXUS_REGISTRY_HOST}/userservice:latest
  only:
    - develop